"""added image column to post table

Revision ID: 51922baed516
Revises: d4b9ae91a836
Create Date: 2018-04-22 16:53:31.500488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51922baed516'
down_revision = 'd4b9ae91a836'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscribers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscribers')
    # ### end Alembic commands ###
