"""update comments table to include an email column

Revision ID: b1c60c6ffc65
Revises: be8c8ff0395c
Create Date: 2018-04-19 15:11:18.300894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c60c6ffc65'
down_revision = 'be8c8ff0395c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
